name: Build Application
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Gradle build
        run: ./gradlew build