name: Build Application
on:
  push:
    branches:
      - 'feature/*'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'

      - name: Unit tests
        run: ./gradlew clean test --info

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: /build/reports/tests/test/index.html

      - name: Gradle build
        run: ./gradlew build

