name: Build Application
on:
  push:
    branches:
      - 'feature/*'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java
          queries: security-and-quality

      - name: Unit tests
        run: ./gradlew clean test --info

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: /build/reports

      - name: Gradle build
        run: ./gradlew build
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
      - name: Upload CodeQL Results
        uses: actions/upload-artifact@v3
        with:
          name: codeql-results
          path: /home/runner/work/BornIn/results/java.sarif
