name: Deploy Application
on: 
  workflow_dispatch:
    inputs:
      deploy:
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
      
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: 'rev-dev-project'
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Hydrate environment
        run: |-
          export DB_USERNAME=${{ secrets.DB_USERNAME }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}

      - name: Unit tests
        run: ./gradlew clean test

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: /build/reports/tests/test/index.html

      - name: Gradle build
        run: ./gradlew build
        
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: Update App Version
        run: 'gcloud app deploy'
      
      
