name: Deploy Application
on: 
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
      
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: 'rev-dev-project'
          credentials_json: ${{ secrets.SERVICE_ACCOUNT }}
      
      - name: Configure app.yaml
        run: |-
          sed -i 's/DB_USER/'${{secrets.DB_USERNAME}}'/g' ./src/main/appengine/app.yaml
          sed -i 's/DB_PASS/'${{secrets.DB_PASSWORD}}'/g' ./src/main/appengine/app.yaml
          sed -i 's/DB_NAME/'${{secrets.DB_NAME}}'/g' ./src/main/appengine/app.yaml
          sed -i 's/DB_IP/'${{secrets.DB_IP}}'/g' ./src/main/appengine/app.yaml
          sed -i 's/DB_CONNECTION/'${{secrets.DB_CONNECTION}}'/g' ./src/main/appengine/app.yaml

      - name: Unit tests
        run: ./gradlew clean test

      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-report
          path: /build/reports/tests/test/index.html

      - name: Gradle build
        run: ./gradlew build
        
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
#
#      - name: Update App Version
#        run: gcloud app deploy

      - name: Serving status
        run: |-
          echo $(gcloud app describe | grep servingStatus) >> $GITHUB_STEP_SUMMARY
          echo "See depployment at https://rev-dev-project.ey.r.appspot.com/" >> $GITHUB_STEP_SUMMARY